#!/bin/bash

url="$1"
web_url="https://app.hey.com"

if [[ $url =~ ^mailto: ]]; then
  email=$(echo "$url" | sed 's/mailto://')
  web_url="https://app.hey.com/messages/new?to=$email"
fi

exec launch-webapp "$web_url"
