#!/bin/bash

if [ "$#" -lt 3 ]; then
  echo "Create new web app:"
  APP_NAME=$(gum input --prompt "Name> ")
  APP_URL=$(gum input --prompt "URL> ")
  ICON_REF=$(gum input --prompt "Icon URL> ")
  CUSTOM_EXEC=""
  MIME_TYPES=""
  INTERACTIVE_MODE=true
else
  APP_NAME="$1"
  APP_URL="$2"
  ICON_REF="$3"
  CUSTOM_EXEC="$4"
  MIME_TYPES="$5"
  INTERACTIVE_MODE=false
fi

if [[ -z "$APP_NAME" || -z "$APP_URL" || -z "$ICON_REF" ]]; then
  echo "Missing fields (name/url/icon)."
  exit 1
fi

ICON_DIR="$HOME/.local/share/applications/icons"
mkdir -p "$ICON_DIR"

if [[ $ICON_REF =~ ^https?:// ]]; then
  ICON_PATH="$ICON_DIR/$APP_NAME.png"
  curl -sL -o "$ICON_PATH" "$ICON_REF" || exit 1
else
  ICON_PATH="$ICON_DIR/$ICON_REF"
fi

if [[ -n $CUSTOM_EXEC ]]; then
  EXEC_COMMAND="$CUSTOM_EXEC"
else
  EXEC_COMMAND="launch-webapp $APP_URL"
fi

DESKTOP_FILE="$HOME/.local/share/applications/$APP_NAME.desktop"

cat > "$DESKTOP_FILE" <<EOD
[Desktop Entry]
Version=1.0
Name=$APP_NAME
Comment=$APP_NAME
Exec=$EXEC_COMMAND
Terminal=false
Type=Application
Icon=$ICON_PATH
StartupNotify=true
EOD

if [[ -n $MIME_TYPES ]]; then
  echo "MimeType=$MIME_TYPES" >> "$DESKTOP_FILE"
fi

chmod +x "$DESKTOP_FILE"

if [[ $INTERACTIVE_MODE == true ]]; then
  echo "Created $APP_NAME (SUPER+SPACE)"
fi
